### ISSUE TITLE
update README with correct url to get file

### ISSUE THREAD

**Issue by Cherviakov** [bfontaine/rfc#15]
curl https://raw.github.com/bfontaine/rfc/master/rfc > ~/bin/rfc - this return file of zero length
curl https://raw.githubusercontent.com/bfontaine/rfc/master/rfc > ~/bin/rfc - that working correctly

Please update

**Comment by bfontaine** [comment]
From the README:

> `curl -sL https://raw.github.com/bfontaine/rfc/master/rfc > ~/bin/rfc`

Your `curl` returns nothing because you forgot `-sL`, or at least `-L`. The former URL redirects to the latter but you need to explicitely tell `cURL` to follow redirections using `-L`:

```
$ curl -i https://raw.github.com/bfontaine/rfc/master/rfc
HTTP/1.1 301 Moved Permanently
Location: https://raw.githubusercontent.com/bfontaine/rfc/master/rfc
Content-Length: 0
...
```

I’ll update the README, nevertheless, thanks for the heads up!
