### ISSUE TITLE
New release for include man page

### ISSUE THREAD

**Issue by NeodarZ** [bfontaine/rfc#16]
Hi,

I want to make an Archlinux package but the man page is not in the latest release.

Can you make a new release who include this man page please?

Thanks for your work!

**Comment by bfontaine** [comment]
Hello, I just released v0.2.6. Thank you for making a package! 🎉

**Comment by NeodarZ** [comment]
Thanks,

for information the package is released: https://aur.archlinux.org/packages/rfc-read/.

It's a different name because the rfc package already exist but the command it's the same for use it: `rfc`.

**Comment by bfontaine** [comment]
Thanks! We could maybe add some instructions in the README for Archlinux users?

**Comment by NeodarZ** [comment]
Why not, I can make a pull request.
